version: "3.8"

services:
  rasa:
    image: rasa/rasa:3.5.10-full
    volumes:
      - ./src/chatbot:/app
    command: run --enable-api --cors "*"
    ports:
      - "5005:5005"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile # Or src/api/Dockerfile if you have one there
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --app-dir src
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    stdin_open: true
    tty: true

  scrapy:
    build:
      context: ./src/scrapers
      dockerfile: Dockerfile
    volumes:
      - ./src/scrapers:/app
    command: scrapy crawl mosdac
