version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j:/data

  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./src/chatbot:/app/src/chatbot
    command: rasa run --enable-api

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app/src/frontend
    depends_on:
      - api

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - neo4j
      - rasa